export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'


export const RELATED_PRODUCT_REQUEST = 'RELATED_PRODUCT_REQUEST'
export const RELATED_PRODUCT_SUCCESS = 'RELATED_PRODUCT_SUCCESS'
export const RELATED_PRODUCT_FAIL = 'RELATED_PRODUCT_FAIL'


export const WATCH_PRODUCT_REQUEST = 'WATCH_PRODUCT_REQUEST'
export const WATCH_PRODUCT_SUCCESS = 'WATCH_PRODUCT_SUCCESS'
export const WATCH_PRODUCT_FAIL = 'WATCH_PRODUCT_FAIL'

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

export const ACTIVE_POSTS_REQUEST = 'ACTIVE_POSTS_REQUEST'
export const ACTIVE_POSTS_SUCCESS = 'ACTIVE_POSTS_SUCCESS'
export const ACTIVE_POSTS_FAIL = 'ACTIVE_POSTS_FAIL'